import tunaImg from "@/assets/tuna-bliss.jpg";
import salmonImg from "@/assets/superior-salmon.jpg";
import glowImg from "@/assets/glow-bowl.jpg";
import veganWishImg from "@/assets/vegan-wish.webp";
import proteinImg from "@/assets/protein-desire.webp";
import falafelImg from "@/assets/falafel-kick.webp";
import chickenSunImg from "@/assets/chicken-sunshine.webp";
import greenSmoothie from "@/assets/green-smoothie.jpg";
import pinkSmoothie from "@/assets/pink-smoothie.jpg";
import kiwiJuice from "@/assets/kiwi-juice.jpg";
import beetJuice from "@/assets/beet-juice.jpg";

export type MenuCategory = "Salads" | "Sandwiches" | "Smoothies" | "Juices" | "Meal Plans";

export type Badge = "Best Seller" | "New Menu" | "Chef's Pick" | "Staff Pick";

export interface MenuItem {
  id: string;
  name: string;
  price: number;
  category: MenuCategory;
  kcal?: string;
  protein?: string;
  badge?: Badge;
  image: string;
  ingredients?: string[];
  tags?: string[];
}

export const MENU: MenuItem[] = [
  // Salads
  {
    id: "tuna-bliss",
    name: "Tuna Bliss",
    price: 5.8,
    category: "Salads",
    kcal: "410 kcal",
    protein: "28g Protein",
    badge: "Best Seller",
    image: tunaImg,
    ingredients: ["Tuna", "Mixed greens", "Cherry tomato", "Olives", "Lemon vinaigrette"],
    tags: ["High protein", "Gluten free"],
  },
  {
    id: "superior-salmon",
    name: "Superior Salmon",
    price: 7.5,
    category: "Salads",
    kcal: "520 kcal",
    protein: "32g Protein",
    badge: "Chef's Pick",
    image: salmonImg,
    ingredients: ["Salmon", "Brown rice", "Cucumber", "Avocado", "Sesame dressing"],
    tags: ["Omega rich", "High protein"],
  },
  {
    id: "glow-bowl",
    name: "Glow Bowl",
    price: 5.2,
    category: "Salads",
    kcal: "420 kcal",
    protein: "22g Protein",
    badge: "Best Seller",
    image: glowImg,
    ingredients: ["Quinoa", "Roasted chickpeas", "Carrot", "Cucumber", "Tahini herb sauce"],
    tags: ["Plant based", "Fiber rich"],
  },
  {
    id: "vegan-garden",
    name: "Vegan Garden",
    price: 5.5,
    category: "Salads",
    kcal: "380 kcal",
    protein: "14g Protein",
    image: veganWishImg,
    ingredients: ["Mixed greens", "Avocado", "Tomato", "Pumpkin seeds", "Balsamic dressing"],
    tags: ["Vegan", "Dairy free"],
  },
  {
    id: "vegan-wish",
    name: "Vegan Wish",
    price: 5.2,
    category: "Salads",
    kcal: "390 kcal",
    protein: "16g Protein",
    badge: "New Menu",
    image: veganWishImg,
    ingredients: ["Falafel", "Baby spinach", "Cucumber", "Red cabbage", "Lemon tahini"],
    tags: ["Vegan", "Plant protein"],
  },
  {
    id: "rice-capitan",
    name: "Rice Capitan",
    price: 6.4,
    category: "Salads",
    kcal: "560 kcal",
    protein: "24g Protein",
    image: glowImg,
    ingredients: ["Brown rice", "Grilled chicken", "Corn", "Black beans", "Yogurt lime sauce"],
    tags: ["Balanced", "High protein"],
  },
  {
    id: "spicy-chicken-origine",
    name: "Spicy Chicken Origine",
    price: 5.8,
    category: "Salads",
    kcal: "470 kcal",
    protein: "30g Protein",
    image: proteinImg,
    ingredients: ["Spicy chicken", "Romaine", "Sweet pepper", "Tomato", "Chipotle dressing"],
    tags: ["Spicy", "High protein"],
  },
  {
    id: "protein-desire",
    name: "Protein Desire",
    price: 6.2,
    category: "Salads",
    kcal: "510 kcal",
    protein: "36g Protein",
    badge: "Staff Pick",
    image: proteinImg,
    ingredients: ["Chicken breast", "Egg", "Edamame", "Spinach", "Mustard vinaigrette"],
    tags: ["High protein", "Low sugar"],
  },

  // Sandwiches
  {
    id: "falafel-kick",
    name: "Falafel Kick",
    price: 3.8,
    category: "Sandwiches",
    kcal: "390 kcal",
    protein: "14g Protein",
    badge: "Best Seller",
    image: falafelImg,
    ingredients: ["Falafel", "Pita", "Lettuce", "Pickled onion", "Tahini sauce"],
    tags: ["Vegetarian", "Plant protein"],
  },
  {
    id: "smoked-salmon",
    name: "Smoked Salmon",
    price: 6.3,
    category: "Sandwiches",
    kcal: "440 kcal",
    protein: "26g Protein",
    badge: "Chef's Pick",
    image: chickenSunImg,
    ingredients: ["Smoked salmon", "Cream cheese", "Cucumber", "Dill", "Seeded bread"],
    tags: ["Omega rich", "High protein"],
  },
  {
    id: "wicked-tuna",
    name: "Wicked Tuna",
    price: 4.0,
    category: "Sandwiches",
    kcal: "410 kcal",
    protein: "24g Protein",
    image: chickenSunImg,
    ingredients: ["Tuna", "Wholegrain bread", "Lettuce", "Tomato", "Light mayo"],
    tags: ["High protein", "Seafood"],
  },
  {
    id: "tasteful-avoegg",
    name: "Tasteful Avoegg",
    price: 4.0,
    category: "Sandwiches",
    kcal: "420 kcal",
    protein: "18g Protein",
    image: falafelImg,
    ingredients: ["Avocado", "Boiled egg", "Spinach", "Tomato", "Sourdough"],
    tags: ["Vegetarian", "Balanced"],
  },
  {
    id: "chicken-energy",
    name: "Chicken Energy",
    price: 4.2,
    category: "Sandwiches",
    kcal: "450 kcal",
    protein: "28g Protein",
    image: chickenSunImg,
    ingredients: ["Grilled chicken", "Wholegrain wrap", "Lettuce", "Corn", "Honey mustard"],
    tags: ["High protein", "Balanced"],
  },
  {
    id: "spicy-chicken",
    name: "Spicy Chicken",
    price: 4.5,
    category: "Sandwiches",
    kcal: "470 kcal",
    protein: "30g Protein",
    image: chickenSunImg,
    ingredients: ["Spicy chicken", "Tortilla", "Slaw", "Jalapeno", "Chipotle sauce"],
    tags: ["Spicy", "High protein"],
  },
  {
    id: "chicken-sunshine",
    name: "Chicken Sunshine",
    price: 4.5,
    category: "Sandwiches",
    kcal: "460 kcal",
    protein: "29g Protein",
    badge: "Staff Pick",
    image: chickenSunImg,
    ingredients: ["Chicken", "Ciabatta", "Arugula", "Roasted pepper", "Lemon aioli"],
    tags: ["High protein", "Fresh"],
  },

  // Smoothies
  {
    id: "green-goodness",
    name: "Green Goodness",
    price: 3.2,
    category: "Smoothies",
    kcal: "210 kcal",
    protein: "6g Protein",
    image: greenSmoothie,
    ingredients: ["Spinach", "Banana", "Green apple", "Lime", "Oat milk"],
    tags: ["Vegan", "Fresh"],
  },
  {
    id: "pb-j",
    name: "PB & J",
    price: 3.2,
    category: "Smoothies",
    kcal: "260 kcal",
    protein: "10g Protein",
    image: pinkSmoothie,
    ingredients: ["Peanut butter", "Strawberry", "Banana", "Oat milk", "Chia"],
    tags: ["Nutty", "Protein boost"],
  },
  {
    id: "almond-boost",
    name: "Almond Boost",
    price: 3.2,
    category: "Smoothies",
    kcal: "240 kcal",
    protein: "9g Protein",
    image: greenSmoothie,
    ingredients: ["Almond butter", "Banana", "Spinach", "Dates", "Almond milk"],
    tags: ["Dairy free", "Energy"],
  },
  {
    id: "peanut-power",
    name: "Peanut Power",
    price: 3.2,
    category: "Smoothies",
    kcal: "290 kcal",
    protein: "12g Protein",
    badge: "Best Seller",
    image: pinkSmoothie,
    ingredients: ["Peanut butter", "Cocoa", "Banana", "Protein yogurt", "Oats"],
    tags: ["High protein", "Nutty"],
  },
  {
    id: "berries-fantasy",
    name: "Berries Fantasy",
    price: 4.2,
    category: "Smoothies",
    kcal: "230 kcal",
    protein: "7g Protein",
    badge: "New Menu",
    image: pinkSmoothie,
    ingredients: ["Strawberry", "Blueberry", "Raspberry", "Banana", "Coconut milk"],
    tags: ["Antioxidant", "Dairy free"],
  },

  // Juices
  {
    id: "kiwi-galore",
    name: "Kiwi Galore",
    price: 3.0,
    category: "Juices",
    kcal: "140 kcal",
    protein: "2g Protein",
    image: kiwiJuice,
    ingredients: ["Kiwi", "Green apple", "Lime", "Mint"],
    tags: ["Vitamin C", "Fresh"],
  },
  {
    id: "ming-energy",
    name: "Ming Energy",
    price: 3.2,
    category: "Juices",
    kcal: "150 kcal",
    protein: "2g Protein",
    image: kiwiJuice,
    ingredients: ["Kiwi", "Cucumber", "Ginger", "Apple"],
    tags: ["Energy", "Cold pressed"],
  },
  {
    id: "pink-lady",
    name: "Pink Lady",
    price: 3.2,
    category: "Juices",
    kcal: "160 kcal",
    protein: "2g Protein",
    badge: "Best Seller",
    image: beetJuice,
    ingredients: ["Beetroot", "Apple", "Lemon", "Ginger"],
    tags: ["Cold pressed", "Vitamin rich"],
  },
  {
    id: "earth-juice",
    name: "Earth Juice",
    price: 3.2,
    category: "Juices",
    kcal: "150 kcal",
    protein: "3g Protein",
    image: beetJuice,
    ingredients: ["Beetroot", "Carrot", "Celery", "Lemon"],
    tags: ["Root blend", "Fresh"],
  },
  {
    id: "green-habit",
    name: "Green Habit",
    price: 3.0,
    category: "Juices",
    kcal: "130 kcal",
    protein: "2g Protein",
    image: kiwiJuice,
    ingredients: ["Spinach", "Cucumber", "Green apple", "Lime"],
    tags: ["Green juice", "Low calorie"],
  },
  {
    id: "heart-juice",
    name: "Heart Juice",
    price: 4.0,
    category: "Juices",
    kcal: "180 kcal",
    protein: "3g Protein",
    badge: "Chef's Pick",
    image: beetJuice,
    ingredients: ["Beetroot", "Pomegranate", "Apple", "Lemon"],
    tags: ["Antioxidant", "Cold pressed"],
  },
  {
    id: "beet-boost",
    name: "Beet Boost",
    price: 3.0,
    category: "Juices",
    kcal: "150 kcal",
    protein: "2g Protein",
    image: beetJuice,
    ingredients: ["Beetroot", "Orange", "Carrot", "Ginger"],
    tags: ["Vitamin rich", "Fresh"],
  },
  {
    id: "carrot-cure",
    name: "Carrot Cure",
    price: 3.2,
    category: "Juices",
    kcal: "140 kcal",
    protein: "2g Protein",
    image: beetJuice,
    ingredients: ["Carrot", "Orange", "Turmeric", "Lemon"],
    tags: ["Vitamin A", "Fresh"],
  },
  {
    id: "celery-vibe",
    name: "Celery Vibe",
    price: 3.2,
    category: "Juices",
    kcal: "120 kcal",
    protein: "2g Protein",
    image: kiwiJuice,
    ingredients: ["Celery", "Cucumber", "Green apple", "Lemon"],
    tags: ["Hydrating", "Low calorie"],
  },
];

export const CATEGORIES: MenuCategory[] = [
  "Salads",
  "Sandwiches",
  "Smoothies",
  "Juices",
  "Meal Plans",
];
